### PR TITLE
Change drop_nulls default in `convert()` to false

### LINKED ISSUE #56: Default for `drop_nulls=True` causes loss of data
When reviewing the number of segmented single cells per image, I noticed a big discrepancy between the output from CytoTable and CellProfiler.

After looking at the CytoTable `convert` function, the parameter `drop_nulls` is defaulted to true, which means that a significant amount of data (rows) is removed due to having at least one column with an NaN value. 

In my original example, I run through a dictionary with paths for each plate to run `convert`:

```python
# run through each run with each set of paths based on dictionary
for plate, info in plate_info_dictionary.items():
    source_path = info["source_path"]
    dest_path = info["dest_path"]
    print(f"Performing merge single cells and conversion on {plate}!")

    # merge single cells and output as parquet file
    convert(
        source_path=source_path,
        dest_path=dest_path,
        dest_datatype=dest_datatype,
        preset=preset,
    )
    print(f"Merged and converted {pathlib.Path(dest_path).name}!")

    # add single cell count per well as metadata column to parquet file and save back to same path
    sc_utils.add_sc_count_metadata_file(
        data_path=dest_path, well_column_name="Image_Metadata_Well", file_type="parquet"
    )
    print(f"Added single cell count as metadata to {pathlib.Path(dest_path).name}!")
```
With the default parameter `drop_nulls` set to true, I get this output for the last variable run in this for loop:

image

After adding the `drop_nulls` parameter to the above function and setting it to False, we get this output for the same plate:

image

Since we preprocess the features before analysis, we can drop columns containing NaN values without removing the segmented single cells entirely. This will be an easy fix to default to False instead and let the user decide if they are okay with removing single cells/rows.

### PR DESCRIPTION
**Pull request by gwaybio**
# Description

Changes the `convert()` default to not drop nulls by default. This is more in-line with expected behavior.

Closes #56

## What is the nature of your change?

- [x] Bug fix (fixes an issue).
- [ ] Enhancement (adds functionality).
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected).
- [ ] This change requires a documentation update.

# Checklist

Please ensure that all boxes are checked before indicating that a pull request is ready for review.

- [x] I have read the [CONTRIBUTING.md](CONTRIBUTING.md) guidelines.
- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] New and existing unit tests pass locally with my changes.
- [x] I have added tests that prove my fix is effective or that my feature works.
- [x] I have deleted all non-relevant text in this pull request template.

### CODE REVIEW

**Review by d33bs — APPROVED** [review]
Cheers, LGTM! Marking this as approved with the understanding that the tests will very likely pass after updating from main. The test failure is I believe unrelated to the changes here and instead pertains to issues which are fixed from the merge of #79.

**Comment by gwaybio** [comment]
Thanks @d33bs - tests pass now, I'm going to merge!

**Comment by gwaybio** [comment]
Tests passed here, but not in the merge: https://github.com/cytomining/CytoTable/actions/runs/5696050273/job/15440405650 🤔

**Comment by d33bs** [comment]
Going to follow up on the errors to investigate further.

**Pull request merged**
