### PR TITLE
Changing python's upper limit version to python<3.12

### PR DESCRIPTION
**Pull request by axiomcura**
# Description

Thank you for your contribution to CytoTable!
Please _succinctly_ summarize your proposed change.
What motivated you to make this change?

This PR addresses the current compatibility issues between `duckdb` and Python 3.12. As `duckdb` does not yet support Python 3.12, it is best to downgrade the upper limit of the Python version in the environment poetry.lock file. 

Below is the current issue 

Issue mentioned: https://github.com/duckdb/duckdb/issues/9301#issuecomment-1756731027
Current PR (however closed) : https://github.com/duckdb/duckdb/pull/9222 

Changes:
* Downgrade the upper limit Python version to Python <3.12 to maintain compatibility with `duckdb`.

Additionally, I have written an issue explaining why Python >3.12 does not work with DuckDB, which directly impacts the installation of CytoTable. #157 

Please also link to any relevant issues that your code is associated with.

## What is the nature of your change?

- [X] Bug fix (fixes an issue).
- [ ] Enhancement (adds functionality).
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected).
- [ ] This change requires a documentation update.

# Checklist

Please ensure that all boxes are checked before indicating that a pull request is ready for review.

- [X] I have read the [CONTRIBUTING.md](CONTRIBUTING.md) guidelines.
- [X] My code follows the style guidelines of this project.
- [X] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [X] My changes generate no new warnings.
- [ ] New and existing unit tests pass locally with my changes.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] I have deleted all non-relevant text in this pull request template.

### CODE REVIEW

**Review by d33bs — COMMENTED** [review]
Thanks @axiomcura ! Looks great. Before an approval, could you make sure there are no changes to the `poetry.lock` file as a result of this change (adding those changes here if there are any updates)?

**Comment by axiomcura** [comment]
Hello @d33bs Just check my editor and no changes that being shown in the poetry.lock file.

**Comment by d33bs** [comment]
Hi @axiomcura , thanks for checking. When updates are made to the `project.toml` dependencies (including the Python version) there typically are lockfile updates to be made. These manifest when running `poetry install` among other places. I recommend running `poetry lock --no-update` to help observe any possible changes.

**Comment by kenibrewer** [comment]
@d33bs we experimented with some of the poetry precommit checks right? I
can't remember which ones we used and why we removed them. I've been using
the poetry lock hook in other repos more recently and it works well and
would catch this pretty common miss.

**Comment by axiomcura** [comment]
Hey @d33bs sorry for the late response, Just ran `poetry lock no-update` there are some changes. Would you like me to push those changes into this PR?

**Comment by d33bs** [comment]
Hi @axiomcura, no worries at all - I suggest updating your forked branch at `axiomcura: python3.11-upperlimit` from `cytomining:main`, re-running `poetry lock --no-update`, and checking that `pre-commit run -a` passes.

**Comment by axiomcura** [comment]
@d33bs poetry-lock file update added!

**Comment by d33bs** [comment]
Hi @axiomcura, thanks! It looks like your forked branch has a conflict that we need to address before merging. Could you update your forked branch from `cytomining:main` and re-run `poetry lock --no-update` (checking that all `pre-commit run -a` also passes)?

**Comment by axiomcura** [comment]
@d33bs I have updated my branch and reran `poetry lock --no-update` should work now!

**Review by d33bs — APPROVED** [review]
Thanks @axiomcura - LGTM! Appreciate your help with this! Please feel free to squash + merge when ready.

**Comment by axiomcura** [comment]
Merging! Thank you!

**Pull request merged**
