### PR TITLE
Add poetry dynamic versioning and update release process

### PR DESCRIPTION
**Pull request by d33bs**
# Description

This PR adds dynamic versioning changes intended to eventually assist with #19 by adding CytoTable version metadata into Parquet output. The goal is to enable dynamic version capture in both development (git source-based) and published releases (PyPI, etc), meaning data created by CytoTable from either path would be accurately versioned (enhancing data provenance / lineage understanding for audiences). While `dunamai` and `__version__` aren't necessarily required yet, I intend to use them with further changes towards #19 and thought early discussion / review / visibility might assist.

As part of this I had to update the release process and tried to practice DRY better with GitHub Actions during the process. I also updated the pre-commit check versions as a general act of good source-keeping.

## What is the nature of your change?

- [ ] Bug fix (fixes an issue).
- [x] Enhancement (adds functionality).
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected).
- [x] This change requires a documentation update.

# Checklist

Please ensure that all boxes are checked before indicating that a pull request is ready for review.

- [x] I have read the [CONTRIBUTING.md](CONTRIBUTING.md) guidelines.
- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] New and existing unit tests pass locally with my changes.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [x] I have deleted all non-relevant text in this pull request template.

### CODE REVIEW

**Review by kenibrewer — APPROVED** [review]
Nice to see this tooling brought to cytotable too! LGTM

**Comment by d33bs** [comment]
Thank you @kenibrewer ! Definitely inspired by your great work in Pycytominer! 🙂

**Comment by d33bs** [comment]
@kenibrewer , thanks again for your review here! Would you like to be a CytoTable maintainer? I feel that the project could benefit from your insights. If so, let me know and I'll send along an invite.

**Comment by kenibrewer** [comment]
@d33bs Sure! I already watch this repo so I can stay aware of the upstream changes that might impact `pycytominer`.  I'd be happy to provide feedback and insights more formally.

**Comment by d33bs** [comment]
Thanks a bunch @kenibrewer - added!

**Pull request merged**
